apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment-{{ include "k8-helm-charts.fullname" . }}
spec:
  replicas: {{ .Values.mariadbReplicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k8-helm-charts.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "k8-helm-charts.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mariadb-{{ .Chart.Name }}
          image: "{{ .Values.mariadbImage.repository }}:{{ .Values.mariadbImage.tag }}"
          imagePullPolicy: {{ .Values.mariadbImage.pullPolicy }}
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "secret"
          ports:
            - name: http
              containerPort: 3306
              protocol: TCP